Dockerfile, Access Control, Locale, Refactoring
kupautist/InnoTyaga pull request #5
Opened 2024-01-13 12:43 UTC by LocalT0aster

## All features

- Dockerfile for easier deployment
- Access control for members with customizable levels of access
- Locale module for easier localization
- Update python to 3.12
- Use fork of [pyTelegramBotAPI](https://github.com/LocalT0aster/pyTelegramBotAPI) with fixes and tweaks
- Lots of refactoring
<img src=https://cdn.discordapp.com/attachments/1058412903901974555/1195708414660186182/PXL_20231206_030221145.jpg width=50%>

2024-01-13 14:32 UTC, da-the-dev requested changes
Impressive work! Needs some fixes though

2024-01-13 14:32 UTC, da-the-dev commented on .gitignore
> +
Should add /.idea folder here as well

2024-01-13 14:32 UTC, da-the-dev commented on .idea/InnoTyaga.iml
I don't we need to track these

2024-01-13 14:32 UTC, da-the-dev commented on .idea/misc.xml
I don't we need to track these

2024-01-13 14:32 UTC, da-the-dev commented on Locale/LocaleRU.py
> +            'Чтобы учавствовать в топе, необходимо зарегистрироваться: /register.\n'
```suggestion
            'Чтобы участвовать в топе, необходимо зарегистрироваться: /register.\n'
```

2024-01-13 14:32 UTC, da-the-dev commented on Locale/LocaleRU.py
> +        'Также иногда проводяться дополнительные занятия, ' \
```suggestion
        'Также иногда проводятся дополнительные занятия, ' \
```

2024-01-13 14:32 UTC, da-the-dev commented on Locale/LocaleRU.py
> +               "Type /help for more information. "
Почему на английском?

2024-01-13 14:32 UTC, da-the-dev commented on Locale/LocaleRU.py
> +    regProblem = 'У вас какие то проблемы с именем или алиасом. Попросите @kupamonke вас зарегистрировать'
```suggestion
    regProblem = 'У вас какиe-то проблемы с именем или алиасом. Попросите @kupamonke вас зарегистрировать'
```

2024-01-13 14:32 UTC, da-the-dev commented on Locale/LocaleRU.py
> +                '/help - посмотреть список всех возможный команд\n'
```suggestion
                '/help - посмотреть список всех возможных команд\n'
```

2024-01-13 14:32 UTC, da-the-dev commented on Locale/LocaleRU.py
> +                '/register - зарегистрироваться в боте. В результате ваши имя и алиас добавяться в топ\n'
```suggestion
                '/register - зарегистрироваться в боте. В результате ваши имя и алиас добавятся в топ\n'
```

2024-01-13 14:32 UTC, da-the-dev commented on Locale/LocaleRU.py
> +                '/newuser - добавить нового участника. В результате чужие имя и алиас появяться в боте.\n'
```suggestion
                '/newuser - добавить нового участника. В результате чужие имя и алиас появятся в боте.\n'
```

2024-01-13 14:32 UTC, da-the-dev commented on Locale/LocaleRU.py
> +                '/olduser - добавить участника которого взвешивали, и который уже пожал. '
```suggestion
                '/olduser - добавить участника, которого взвешивали, и который уже пожал. '
```

2024-01-13 14:32 UTC, da-the-dev commented on Locale/LocaleRU.py
> +                'В результате его результаты появяться в топе.\n'
```suggestion
                'В результате его результаты появятся в топе.\n'
```

2024-01-13 14:32 UTC, da-the-dev commented on requirements.txt
I think we should wait for the changes on the fork to be merged into pyTelegramBotAPI instead of using the fork. This would be safer, since the fork might divert from the main repo

2024-01-13 14:32 UTC, da-the-dev commented on test.ipynb
Is this notebook needed?

2024-01-13 14:32 UTC, da-the-dev commented on .build.sh
I don't think we need this file. We have instructions in README anyway

2024-01-14 19:39 UTC, da-the-dev requested changes
Looks even better! After fixing some minor things here and there, I think we'll be ready to merge!

2024-01-14 19:39 UTC, da-the-dev commented on Locale/LocaleEn.py
> +             'To display the available commands, type /help.\n'
```suggestion
             'To display available commands, type /help.\n'
```

2024-01-14 19:39 UTC, da-the-dev commented on Locale/LocaleEn.py
> +             'To display the all-time top participants, write /top.\n'
```suggestion
             'To display all-time top participants, write /top.\n'
```

2024-01-14 19:39 UTC, da-the-dev commented on Locale/LocaleEn.py
> +    alreadyRegistred = 'The member is already registered'
```suggestion
    alreadyRegistred = 'This member is already registered'
```

2024-01-14 19:39 UTC, da-the-dev commented on Locale/LocaleEn.py
> +    emptyTop = 'No members in top now.\nYou can add members to top using /olduser or /newuser commands.\n' \
```suggestion
    emptyTop = 'No members in the top now.\nYou can add members to the top using /olduser or /newuser commands.\n' \
```

2024-01-14 19:39 UTC, da-the-dev commented on Locale/LocaleEn.py
> +    goodPhoto = 'Quite a photo. I give it an 8.5 out of 10.'
```suggestion
    goodPhoto = 'Quite a photo. I give it 8.5 out of 10.'
```

2024-01-14 19:39 UTC, da-the-dev commented on Locale/LocaleEn.py
> +                "/schedule - see the schedule of training sessions.\n"
```suggestion
                "/schedule - see the schedule of the training sessions.\n"
```

2024-01-14 19:39 UTC, da-the-dev commented on Locale/LocaleEn.py
> +                "/delete - remove a member from the top.",
```suggestion
                "/delete - remove the member from the top.",
```

2024-01-14 19:39 UTC, da-the-dev commented on Locale/LocaleEn.py
> +    accessDenied = "You do not have access to this command. If you think there's been an error, email @kupamonke"
```suggestion
    accessDenied = "You do not have access to this command. If you think there's been an error, ask @kupamonke"
```

2024-01-14 19:39 UTC, da-the-dev commented on Locale/LocaleEn.py
> +    deleting = 'Removing a member...'
```suggestion
    deleting = 'Removing member...'
```

2024-01-14 19:39 UTC, da-the-dev commented on README.md
> +InnoTyaga is an unofficial club in Innopolis, boasting over 30 active members. This python bot was developed by @kupamonke to aid in the management of the club, particularly with handling points calc
```suggestion
InnoTyaga is an unofficial sports club in Innopolis, boasting over 30 active members. This python bot was developed by @kupamonke, @NeRaG0n7, and partially by @fatcakes to aid in the management of the club, particularly with handling points calculation for each member and automatically updating the leaderboard.
```

2024-01-14 19:39 UTC, da-the-dev commented on README.md
> +InnoTyaga is an unofficial club in Innopolis, boasting over 30 active members. This python bot was developed by @kupamonke to aid in the management of the club, particularly with handling points calc
You earned the credit, especially after all that hard work

2024-01-15 10:54 UTC, da-the-dev requested changes
Added changes related to @kupautist's request...

2024-01-15 10:54 UTC, da-the-dev commented on Locale/LocaleRu.py
> +        'информацию по которым можно найти в основной беседе клуба: @innotyaga'
```suggestion
    schedule = 'Да похуй всем Серёжа Допизделся) Лучше выложи расклад карт таро на твою ЛЕГЕНДАРНЕЙШЕЮ "Прошедшей ночью данные ребята ломились не в свою квартиру в 130 доме. При вопросе "чонада" свалили в закат. Наверное дом перепутали. Или город. Короче скоро новый год и иронию судьбы косплеели ребята...надеюсь...\nГоворят местные перепутали 130 и 114 дом." в Иннополисе мы все ждем'  \
    'Основная информация по вечно меняющемуся рассписанию в офф канале @innotyaga'
```
As per @kupautist's request...

2024-01-15 10:54 UTC, da-the-dev commented on Locale/LocaleEn.py
> +        "There are also occasional extra classes, information on which can be found in the club's main chat: @innotyaga"
```suggestion
    schedule = 'Да похуй всем Серёжа Допизделся) Лучше выложи расклад карт таро на твою ЛЕГЕНДАРНЕЙШЕЮ "Прошедшей ночью данные ребята ломились не в свою квартиру в 130 доме. При вопросе "чонада" свалили в закат. Наверное дом перепутали. Или город. Короче скоро новый год и иронию судьбы косплеели ребята...надеюсь...\nГоворят местные перепутали 130 и 114 дом." в Иннополисе мы все ждем'  \
    'Info on the ever-changing class schedule subscribe to the official info channel @innotyaga'
```
As per @kupautist's request...

2024-01-15 15:18 UTC, da-the-dev approved these changes
Approved!

2024-01-18 13:56 UTC, merged

2024-01-18 13:57 UTC, kupautist reviewed
Great job!